cjw_config_processing.index:
  path: /cjw/config-processing
  defaults:
    _controller: cjw_config_processor.controller:getStartPage
    _methods: [GET]

cjw_config_processing.param_list:
  path: /cjw/config-processing/parameter_list
  defaults:
    _controller: cjw_config_processor.controller:getParameterList
    _methods: [GET]

cjw_config_processing.site_access_param_list:
  path: /cjw/config-processing/parameter_list/siteaccess/{siteAccess}
  defaults:
    _controller: cjw_config_processor.controller:getSpecificSAParameters
    _methods: [GET]
    siteAccess: null

cjw_config_processing.compare_site_accesses:
  path: /cjw/config-processing/parameter_list/compare/{firstSiteAccess}/{secondSiteAccess}/{limiter}
  defaults:
    _controller: cjw_config_processor.controller:compareSiteAccesses
    _methods: [GET]
    limiter: null;

cjw_config_processing.param_list_favourites:
  path: /cjw/config-processing/parameter_list/favourites/{siteAccess}
  defaults:
    _controller: cjw_config_processor.controller:getFavourites
    _methods: [GET]
    siteAccess: null

cjw_config_processing.get_favourite_keys:
  path: /cjw/config-processing/parameter_list/keylist/favourites
  defaults:
    _controller: cjw_config_processor.controller:getFavouriteKeyList
    _methods: [GET]

cjw_config_processing.save_favourites:
  path: /cjw/config-processing/parameter_list/save/favourites
  defaults:
    _controller: cjw_config_processor.controller:saveFavourites
    _methods: [POST]

cjw_config_processing.remove_favourites:
  path: /cjw/config-processing/parameter_list/remove/favourites
  defaults:
    _controller: cjw_config_processor.controller:removeFavourites
    _methods: [POST]

cjw_config_processing.download_parameters:
  path: /cjw/config-processing/parameter_list/download/{downloadDescriptor}
  defaults:
    _controller: cjw_config_processor.controller:downloadParameterListAsTextFile
    _methods: [GET]

# Location Retrieval from different controller:
cjw_config_processing.location_retrieval:
  path: /cjw/config-processing/parameter_locations/{parameter}/{withSiteAccess}
  defaults:
    _controller: cjw_config_processor.location_controller:retrieveLocationsForParameter
    _methods: [GET]
    withSiteAccess: "false"
