services:
  cjw_config_processor.twig.display:
    class: CJW\CJWConfigProcessor\Services\TwigConfigDisplayService
    arguments:
      ["@service_container", "@ezpublish.config.resolver", "@request_stack"]
    tags:
      - { name: twig.extension }

  cjw_location_aware_config_load_bundle.twig.display:
    class: CJW\CJWConfigProcessor\Services\TwigTestDisplayService
    tags:
      - { name: twig.extension }

  cjw_config_processor.controller:
    class: CJW\CJWConfigProcessor\Controller\ConfigProcessController
    arguments:
      ["@service_container", "@ezpublish.config.resolver", "@request_stack"]
    public: true

  cjw_location_retrieval.controller:
    class: CJW\CJWConfigProcessor\Controller\ConfigProcessLocationInfoController
    arguments: [ "@service_container", "%kernel.project_dir%" ]
    public: true

  # menu builders for the frontend
  cjw_config_processing.menu.subscriber:
    class: CJW\CJWConfigProcessor\EventSubscriber\ConfigProcessingMenuSubscriber
    tags:
      - { name: kernel.event_subscriber }

  cjw_config_processing.left.sidebar.builder:
    class: CJW\CJWConfigProcessor\EventSubscriber\LeftSideBarMenuBuilder
    autowire: true
    autoconfigure: true
    public: true
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: cjw_config_processing.menu.sidebar_left }

  cjw_config_processing.right.site_access_comparison.sidebar.builder:
    class: CJW\CJWConfigProcessor\EventSubscriber\RightSideBarSiteAccessComparisonMenuBuilder
    autowire: true
    autoconfigure: true
    public: true
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: cjw_config_processing.menu.site_access_comparison.sidebar_right }
