cjw_config_processing.index:
  path: /cjw/config-processing
  controller: cjw_config_processor.controller::getStartPage
  methods: [GET]

cjw_config_processing.param_list:
  path: /cjw/config-processing/parameter_list
  controller: cjw_config_processor.controller::getParameterList
  methods: [GET]

cjw_config_processing.site_access_selection:
  path: /cjw/config-processing/siteaccess_list
  controller: cjw_config_processor.controller::siteAccessSelection
  methods: [GET]

cjw_config_processing.site_access_param_list:
  path: /cjw/config-processing/parameter_list/siteaccess/current
  controller: cjw_config_processor.controller::getCurrentSAParameters

cjw_config_processing.specific_site_access_param_list:
  path: /cjw/config-processing/parameter_list/siteaccess/{siteAccess}
  controller: cjw_config_processor.controller::getSpecificSAParameters
  methods: [GET]

cjw_config_processing.compare_site_accesses:
  path: /cjw/config-processing/parameter_list/compare/{firstSiteAccess}/{secondSiteAccess}
  controller: cjw_config_processor.controller::compareSiteAccesses
  methods: [GET]

cjw_config_processing.compare_site_accesses.commons_only:
  path: /cjw/config-processing/parameter_list/compare/{firstSiteAccess}/{secondSiteAccess}/commons
  controller: cjw_config_processor.controller::compareSiteAccessesCommonsOnly
  methods: [GET]

cjw_config_processing.compare_site_accesses.uncommons_only:
  path: /cjw/config-processing/parameter_list/compare/{firstSiteAccess}/{secondSiteAccess}/uncommons
  controller: cjw_config_processor.controller::compareSiteAccessesUncommonsOnly
  methods: [GET]

cjw_config_processing.location_retrieval:
  path: /cjw/config-processing/parameter_locations/{parameter}
  controller: cjw_location_retrieval.controller::retrieveLocationsForParameter
  methods: [GET]

