# This file stores all directories the LoadInitializer is supposed to go through when trying to parse the configuration while keeping
# track of the location the values are retrieved from.
parameters:
  # Routes are built in the following format:
  # routename: {path: the/absolute/path/to/the/resource.TheExtensionsToSearchForThere, glob: true/false (is it a glob pattern?), addConfExt: true/false}
  # Example route: example: {path: ezinstallation/src/bundle/resources/config/*.yaml, glob: false, addConfExt: false}

  #  route: {path: testpath/src/bundle/resources/services.yaml, glob: false, addConfExt: false}

  # Secondly: The third parameter of the route: "addConfExt", will (when "glob" is set to "true") add the known config extensions automatically to the route
  # Example: secondRoute: {path: ezinstallation/some/bundle/some/conf/directory, glob: true, addConfExt: true)}
  # This will then add the known config extensions, when the route is being parsed.

  #  secondRoute: {path: ezinstallation/some/bundle/some/conf/directory/*, glob: true, addConfExt: true)}
  #  fourthRoute: {path: /mnt/data/htdocs/bicycleLearning/ezplatform/src/CJWLocationAwareConfigLoadBundle/Resources/config/services.yaml, glob: true, addConfExt: true}
  testRoute:
    {
      path: /mnt/data/htdocs/bicycleLearning/ezplatform/src/CJW/LocationAwareConfigLoadBundle/Resources/config/test.yaml,
      glob: false,
      addConfExt: false,
    }
